# path: ./docker-compose.yml
version: '3'

services:
  app:
    build:
      context: .
    container_name: "frontend"
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev